### ISSUE TITLE
NameError: name 'false' is not defined

### ISSUE THREAD

**Issue by Mehliug-git** [milosilo/hack_hard#1]
I have the error :
NameError: name 'false' is not defined

I think you want False not 'false'

**Comment by milosilo** [comment]
On which line of code?

**Comment by Mehliug-git** [comment]
![image](https://github.com/milosilo/hack_hard/assets/78538454/959cd99c-3151-4f49-ae21-a7642343ce40)
 IDK I just have this

**Comment by milosilo** [comment]
Are you trying to clone the repo? I see some things in there that i don't look like it's part of the game.

**Comment by milosilo** [comment]
Inactive
